/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-07-22 13:57:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class upload_005fdownload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>下载上传文件</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 如果upload_download.jsp不在根目录下，在“项目根目录/jsp”文件夹下那么 相对路径写法“download”就访问不到对应的请求方法，因为路径成了“/SpringMVCTest007/jsp/download”\r\n");
      out.write("\t\t因此要写绝对路径访问请求方法\r\n");
      out.write("\t-->\r\n");
      out.write("\t<a href=\"/SpringMVCTest007/download\" >下载</a>   <br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<font size=\"4px\" color=\"red\" >上传文件（只用IO流）</font>\r\n");
      out.write("\t<form action=\"/SpringMVCTest007/upload\" method=\"post\"  enctype=\"multipart/form-data\" >   <!-- 注意这里是 form 和data之间是横线，不是冒号 -->\r\n");
      out.write("\t\t图片：<input type=\"file\"  name=\"uploadFile\"></input>      <br>\r\n");
      out.write("\t\t描述：<input type=\"text\"  name=\"description\"></input>     <br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"上传\"></input>                <br>\r\n");
      out.write("\t</form> \r\n");
      out.write("\t\r\n");
      out.write("\t<font size=\"4px\" color=\"red\" >上传文件（用Spring框架的MultipartFile对象）</font>\r\n");
      out.write("\t<form action=\"/SpringMVCTest007/uploadNew\" method=\"post\"  enctype=\"multipart/form-data\" >   <!-- 注意这里是 form 和data之间是横线，不是冒号 -->\r\n");
      out.write("\t\t图片：<input type=\"file\"  name=\"uploadFile\"></input>      <br>\r\n");
      out.write("\t\t描述：<input type=\"text\"  name=\"description\"></input>     <br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"上传\"></input>                <br>\r\n");
      out.write("\t</form> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
